** BFC
*** Box： CSS布局的基本单位 　　
Box 是 CSS 布局的对象和基本单位， 直观点来说，就是一个页面是由很多个 Box 组成的。元素的类型和 display 属性，决定了这个 Box 的类型。 不同类型的 Box， 会参与不同的 Formatting Context（一个决定如何渲染文档的容器），因此Box内的元素会以不同的方式渲染。让我们看看有哪些盒子：
block-level box:display 属性为 block, list-item, table 的元素，会生成 block-level box。并且参与 block fomatting context； inline-level box:display 属性为 inline, inline-block, inline-table 的元素，会生成 inline-level box。并且参与 inline formatting context； run-in box: css3 中才有， 这儿先不讲了。
*** Formatting context：Formatting context 是 W3C CSS2.1 规范中的一个概念
它是页面中的一块渲染区域，并且有一套渲染规则，它决定了其子元素将如何定位，以及和其他元素的关系和相互作用。最常见的 Formatting context 有 Block fomatting context (简称BFC)和 Inline formatting context (简称IFC)。
CSS2.1 中只有 BFC 和 IFC, CSS3 中还增加了 GFC 和 FFC。
*** BFC 定义：BFC(Block formatting context)直译为"块级格式化上下文"
它是一个独立的渲染区域，只有Block-level box参与， 它规定了内部的Block-level Box如何布局，并且与这个区域外部毫不相干。
** BFC布局规则
*** BFC是页面上的隔离的独立容器，容器里面的子元素不会影响到外面的元素。反之也如此
*** 内部Box会在垂直方向，一个接一个放置。属于同一个BFC的两个相邻Box的margin会发生重叠；每个元素与包含块的box的左边接触(对于从左往右的格式化，否则相反)。即使有浮动也是如此
*** BFC的区域不会与float box重叠
*** 计算BFC的高度时，浮动元素也参与计算
** 生成BFC的元素
*** 根元素
*** float属性不为none
*** position为absolute或fixed
*** display为inline-block, table-cell, table-caption, flex, inline-flex
*** overflow不为visible
